### PR TITLE
V8 requires C++17

### PR DESCRIPTION
**Pull request by JanMarvin**
Most likely not the commit you want, R is finally at C++14 and will remain there for 4.2? We could parse `<v8-version.h>` in the configure file to get the version number or set `CXX17` if supported just like we did with `CXX14`?

### CODE REVIEW

**Comment by jeroen** [comment]
Hmm I guess this breaks the build on systems that support C++14 but not C++17?

**Comment by JanMarvin** [comment]
Likely, though unsure which specific GCC/clang versions support which c++ standard. Maybe the currently used ones in Windows R already support C++17. The CI ones here do not seem to bother, the failing one is because of CRT(?) and looks unrelated to the changes. I could think of a few ways forward, but maybe you have a preference for something. Avoiding C++17/20 only buys a moment of time, iirc Google has already made C++17 their default (though I'm not sure where I read it).

**Comment by jeroen** [comment]
Ah hmm it is more complicated than I thought. If we enable C++17 we actually break the build for older versions of libv8 because many features have been deprecated. So we should really only opt-in to CXX17 when using libv8 10+...

**Comment by JanMarvin** [comment]
I have pushed changes that fetch the precompiler macros using whatever c++ compiler is available, fetch the V8_MAJOR_VERSION and set different compilers for major versions 8 and 10.

**Comment by JanMarvin** [comment]
Thanks, closing because solved differently. I though that checking v8-major would be sufficient, but ofc it might limit the compiler version to whatever outdated v8 one runs :)

**Comment by jeroen** [comment]
Yeah I'm sorry for changing my mind on this. Trying to find the most robust solution that will work on different combinations of compilers and versions of v8 is tricky. But I went basically with your original suggestion to opt-in to C++17 when possible.

Thanks for raising this :)

**Pull request closed without merging**
