### PR TITLE
check args.Length fixes #70

### LINKED ISSUE #70: r callback is broken in v8 7.9.151
This 
```
ctx$eval('//get a data frame
    var iris = console.r.get("iris")
    var iris_col = console.r.get("iris", {dataframe:"col"})
  ')
```
breaks with 
`Evaluation error: unused argument ("undefined").`

In the lines below `val` and `json` are undefined. Not sure what's going on. Heading to work now. Must be due to some upstream changes in v8 over the last seven days.https://github.com/jeroen/V8/blob/46f26a1290985c173c28ec68927fca6ae8e5dea1/src/bindings.cpp#L108-L114

### PR DESCRIPTION
**Pull request by JanMarvin**
I assume the issue #70 is caused by https://github.com/v8/v8/commit/089a48813b457d049befb11069cff824ce0e7dee though I am not sure. Fix appears to be backward compatible

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! It's probably safer to reverse the conditions, i.e first check the length and only then test if the element at that length is undefined.

**Comment by jeroen** [comment]
Thanks!

**Comment by jeroen** [comment]
By the way, can you maybe suggest a section for the readme file how to install v8-r on arch? I don't use arch myself, but I tried `pacman -S v8-r` in a docker container and that didn't work :)

**Comment by JanMarvin** [comment]
Regarding the AUR Arch is a bit tricky. The AUR is just a repository of PKGBUILDs that have to be build. If you want to install and update packages from the AUR, you need an [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers). This can be an independent program or a wrapper around `pacman`. I use [`trizen`](https://github.com/trizen/trizen) as AUR helper, so for me it's just `trizen -S v8-r`, but there are other AUR helpers and there is no general way. For a readme the best recommendation is probably to install `v8-r` from the AUR. Arch users and users of Arch based distributions will know what to do. If one wants to avoid AUR helpers altogether, it is possible to download a snapshot from the AUR, untar it, cd into the folder and run `makepkg -i`.

**Pull request merged**
