### PR TITLE
v8 8.7.80 requires c++14

### PR DESCRIPTION
**Pull request by JanMarvin**
V8 8.7.80 requires c++14 using `std::remove_cv_t`. I switched `CXX` to `CXX14` and `CXXFLAGS` to `CXX14FLAGS`. Might require adding it as SystemRequirements in DESCRIPTION and ofc this is not required with the legacy implementation and most likely breaks on systems without a c++14 compiler (something I do not have at hand). 

In a second step I removed `CPPFLAGS` used for building the pointer_compression test otherwise v8 would complain about building without `-O`.

### CODE REVIEW

**Comment by JanMarvin** [comment]
https://github.com/v8/v8/blob/master/include/v8-internal.h#L418 is the line introduced in https://github.com/v8/v8/commit/74ede0710396b4aa4a53f4e4ce71cdf944a968ad

**Comment by jeroen** [comment]
Hmm I don't think we can do this unconditionally because that will break on systems with older v8/gcc.

**Comment by JanMarvin** [comment]
Hehe, the comment I expected. I'll see if I can come up with something. Might involve calling `d8` for the V8 version, asking R if it's C++14 ready or a tiny regex modification of v8.h since we don't need the test suite to compile.

Anyways that's another little thing upstream could inform about in a config file.

**Comment by jeroen** [comment]
Does it help if we just remove `CXX_STD=CXX11` from `src/Makevars`? In that case it should use the default c++ standard, which is c++14 on most modern gcc versions.

**Comment by JanMarvin** [comment]
My current `/etc/R/Makeconf` from contains `CXX = g++ -std=gnu++11` which will be used for linking if the package Makefile is ignored. I think until R will adopt c++14 as default a different solution must be found. Though I haven't looked into it yet, might have some time the upcoming weekend.

**Comment by JanMarvin** [comment]
Pushed an alternative approach calculating the V8 version number and enabling C++14 if required. This way it should not interfere with anything below V8 version 8.7.77, but this requires a `v8-version.h` file (not sure how long this file does exists). Simply including `v8.h` does not work as the build might break for the pointer compression check further down in the configure file.

The calculated number can be used to identify the legacy versions as well, though the specific line might need some more tweaking.

**Comment by JanMarvin** [comment]
Travis tells me that `v8-version.h` is not available with v8 3.14 and back to the drawing board.

**Comment by jeroen** [comment]
Thanks for looking into it. Is the `std::remove_cv_t` thing the only call that requires CXX14? Perhaps we can ask on the mailing list if they can revert this? What error do you get?

**Comment by JanMarvin** [comment]
Currently it's only this single line. We might ask them to remove the line, which might or might not resolve the problem anytime soon. My approach is ignoring that they mess with a single line and instead provide a future ready approach.

A quick and dirty solution might be to add this check after the compiler-compression check, ignoring the legacy version. Though I do not find it very elegant and tried to combine two compile checks into a single one.

The corresponding build error I'm getting is here: https://gist.github.com/JanMarvin/d50de84495c4af84e480764c82825e17.

**Comment by JanMarvin** [comment]
The Apple builds might require something like the following but this appears to be unrelated to this pull request
```
#if defined( __APPLE__ )
#undef static_assert
#endif
```

**Comment by JanMarvin** [comment]
Please let me know if you have any further comments or ideas how to solve the issue. V8 branched again and is already at 8.8.56

**Pull request closed without merging**
