### PR TITLE
initial work on modules

### PR DESCRIPTION
**Pull request by JanMarvin**
A messy little something for #176

### CODE REVIEW

**Comment by jeroen** [comment]
I'm first going to try something that does not change the R API: https://github.com/jeroen/V8/pull/179

**Comment by JanMarvin** [comment]
Understandable, I was just toying around on the basis of your issue 👍

**Comment by jeroen** [comment]
Yeah its fun tinkering with these things. Does the current master branch seem ok with the latest arch v8-R?

**Comment by JanMarvin** [comment]
Yes, works fine. Running  the test required a `setwd("test/testthat")`, otherwise fine

**Pull request closed without merging**
