### PR TITLE
GetContents() was depreached and removed

### PR DESCRIPTION
**Pull request by JanMarvin**
in https://chromium.googlesource.com/v8/v8.git/+/578f6be77fc5d8af975005c2baf918e7225abb62%5E%21/#F0

Lets see what CI says to this

### CODE REVIEW

**Comment by JanMarvin** [comment]
Kinda hoped, that CI would be green. Let me know how you like this approached. Switching functions via define?

**Comment by jeroen** [comment]
Yes conditioning on the new version using a macro as we do elsewhere in the
code I think.

Op vr 19 mrt. 2021 15:44 schreef Jan Marvin Garbuszus <
***@***.***>:

**Comment by JanMarvin** [comment]
I have added the `#if` and `#else` conditioning to the V8 release that removes the function (in theory some earlier versions should be fine too, but did not want to search for any specific version and it should not matter anyway)

**Comment by jeroen** [comment]
Thanks!

**Comment by jeroen** [comment]
Hmm CRAN has now upgraded to Fedora-36, which has libv8 9.4 and now this sanitizer warning appears:

```
/usr/include/c++/12/bits/shared_ptr_base.h:1071:21: runtime error: member call on address 0x603000072d60 which does not point to an object of type '_Sp_counted_base'
0x603000072d60: note: object has invalid vptr
 00 00 00 00  50 4e 27 9c f7 7f 00 00  02 00 00 00 02 00 00 00  40 5d 01 00 60 60 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x7ff79c551727 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/12/bits/shared_ptr_base.h:1071
    #1 0x7ff79c551727 in std::__shared_ptr<v8::BackingStore, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/12/bits/shared_ptr_base.h:1524
    #2 0x7ff79c551727 in std::shared_ptr<v8::BackingStore>::~shared_ptr() /usr/include/c++/12/bits/shared_ptr.h:175
    #3 0x7ff79c551727 in convert_object /data/gannet/ripley/R/packages/tests-gcc-SAN/V8/src/bindings.cpp:212
```

No idea what the problem is though, but it appears in both places where we call `GetBackingStore()`

**Comment by JanMarvin** [comment]
Looking at [the report](https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/V8/V8-Ex.Rout) it might be a false positive, since the test succeeds? I'll see if I can reproduce this locally.

**Comment by jeroen** [comment]
The tests always succeed, that is the not the issue. But apparently it is doing something illegal :/

**Comment by JanMarvin** [comment]
Could not replicate this with `rocker/r-devel-ubsan-clang` using `libv8-dev` and this goes a bit above my C++ knowledge, but:
* it might be a false positive [looking at this SO](https://stackoverflow.com/questions/57294792/c-ubsan-produces-false-positives-with-derived-objects) (maybe vtables in v8 and libv8 are different) and
* in v8 there are a few commits regarding sanitizers, tough nothing that was obvious and they all were ages old

**Pull request merged**
