### PR TITLE
check if v8 works with pointer compression. fixes #78

### LINKED ISSUE #78: tests fail with v8 8.1.63
Just to inform you, recent changes cause a crash in v8.

```R
==> devtools::test()

Loading V8
Using V8 engine 8.1.63
Testing V8
✓ |  OK F W S | Context
⠏ |   0       | JS ArrayBuffers
 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: .Call("_V8_context_eval", PACKAGE = "V8", src, ctx, serialize)
 2: context_eval(join(src), private$context, serialize)
 3: identical(str, "undefined")
 4: get_str_output(context_eval(join(src), private$context, serialize))
 5: evaluate_js(name, serialize = TRUE)
 6: get_json_output(evaluate_js(name, serialize = TRUE), ...)
 7: ctx$get("data")
 8: eval_bare(expr, quo_get_env(quo))
 9: quasi_label(enquo(object), label, arg = "object")
10: expect_equal(ctx$get("data"), 1:3)
11: eval(code, test_env)
12: eval(code, test_env)
13: withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch(withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error), error = handle_fatal,     skip = function(e) {    })
21: test_code(desc, code, env = parent.frame())
22: test_that("Reading and writing raw buffers", {    ctx <- V8::v8()    ctx$eval("\nvar data = [1,2,3]\nvar intArray = new Uint8Array( data )\nvar dataBuffer = new ArrayBuffer( 3 )\nvar floatArray = new Float32Array( [0, Math.PI])")    expect_equal(ctx$get("data"), 1:3)    expect_equal(ctx$get("dataBuffer"), raw(3))    expect_equal(ctx$get("floatArray"), as.raw(c(0, 0, 0, 0,         219, 15, 73, 64)))    expect_equal(ctx$get("intArray"), as.raw(1:3))    expect_equal(ctx$eval("dataBuffer"), "[object ArrayBuffer]")    expect_equal(ctx$eval("floatArray.buffer"), "[object ArrayBuffer]")    expect_equal(ctx$eval("intArray.buffer"), "[object ArrayBuffer]")})
23: eval(code, test_env)
24: eval(code, test_env)
25: withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error)
26: doTryCatch(return(expr), name, parentenv, handler)
27: tryCatchOne(expr, names, parentenv, handlers[[1L]])
28: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
29: doTryCatch(return(expr), name, parentenv, handler)
30: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
31: tryCatchList(expr, classes, parentenv, handlers)
32: tryCatch(withCallingHandlers({    eval(code, test_env)    if (!handled && !is.null(test)) {        skip_empty()    }}, expectation = handle_expectation, skip = handle_skip, warning = handle_warning,     message = handle_message, error = handle_error), error = handle_fatal,     skip = function(e) {    })
33: test_code(NULL, exprs, env)
34: source_file(path, new.env(parent = env), chdir = TRUE, wrap = wrap)
35: force(code)
36: doWithOneRestart(return(expr), restart)
37: withOneRestart(expr, restarts[[1L]])
38: withRestarts(testthat_abort_reporter = function() NULL, force(code))
39: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter,     {        reporter$start_file(basename(path))        lister$start_file(basename(path))        source_file(path, new.env(parent = env), chdir = TRUE,             wrap = wrap)        reporter$.end_context()        reporter$end_file()    })
40: FUN(X[[i]], ...)
41: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE, load_helpers = FALSE, wrap = wrap)
42: force(code)
43: doWithOneRestart(return(expr), restart)
44: withOneRestart(expr, restarts[[1L]])
45: withRestarts(testthat_abort_reporter = function() NULL, force(code))
46: with_reporter(reporter = current_reporter, results <- lapply(paths,     test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE,     load_helpers = FALSE, wrap = wrap))
47: test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,     stop_on_warning = stop_on_warning, wrap = wrap)
48: (function (path, filter = NULL, reporter = default_reporter(),     env = test_env(), ..., encoding = "unknown", load_helpers = TRUE,     stop_on_failure = FALSE, stop_on_warning = FALSE, wrap = TRUE) {    if (!missing(encoding) && !identical(encoding, "UTF-8")) {        warning("`encoding` is deprecated; all files now assumed to be UTF-8",             call. = FALSE)    }    testthat_dir <- maybe_root_dir(path)    withr::local_envvar(list(R_TESTS = "", TESTTHAT = "true",         TESTTHAT_DIR = testthat_dir))    if (load_helpers) {        source_test_helpers(path, env)    }    source_test_setup(path, env)    on.exit(source_test_teardown(path, env), add = TRUE)    if (identical(Sys.getenv("NOT_CRAN"), "true")) {        withr::local_options(list(lifecycle_verbose_retirement = TRUE))    }    paths <- find_test_scripts(path, filter, ...)    test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,         stop_on_warning = stop_on_warning, wrap = wrap)})("/home/jmg/Source/V8/tests/testthat", filter = NULL, env = <environment>,     stop_on_failure = FALSE, load_helpers = FALSE)
49: do.call(testthat::test_dir, testthat_args)
50: force(code)
51: withr::with_envvar(c(r_env_vars(), TESTTHAT_PKG = pkg$package),     do.call(testthat::test_dir, testthat_args))
52: force(code)
53: withr::with_options(c(useFancyQuotes = FALSE), withr::with_envvar(c(r_env_vars(),     TESTTHAT_PKG = pkg$package), do.call(testthat::test_dir,     testthat_args)))
54: devtools::test()
An irrecoverable exception occurred. R is aborting now ...
```

### PR DESCRIPTION
**Pull request by JanMarvin**
Second attempt 

1) Compile a test program, which runs Initialize().
2) Capture if it crashes.
3) Set compile flags accordingly.

### CODE REVIEW

**Comment by JanMarvin** [comment]
Tested with v8 8.4.118 built with `v8_enable_pointer_compression=` true/false

**Comment by jeroen** [comment]
This is such a hassle. I've added my comment to the upstream issue that the solution they provided doesn't solve anything: https://bugs.chromium.org/p/v8/issues/detail?id=10041

Thanks for your help!

**Comment by JanMarvin** [comment]
Thanks for the heads up. The solution in this pr works (at least with non legacy builds). I've tested it with v8 builds with and without pointer compression. It is not what I was expecting (a configure flag), but imho it's not completely useless

**Comment by jeroen** [comment]
The thing that worries me about this solution is that if ` inst/test.cpp` fails to compile or run for completely unrelated reasons (linking error or what not), we arrive at the wrong conclusion that it must be the pointer compression...

**Comment by JanMarvin** [comment]
I've considered it and there is such a failure happening with some of the osx builds without homebrew iirc. I didn't consider such a failure as important because if this initial attempt to build fails the entire build fails. The test program in this pr uses only the flags and the compiler that are passed down to the full build moments later. Still I agree that another solution with config flags would be better.

**Comment by jeroen** [comment]
I'm going to wait if upstream makes further changes because they reopened the ticket: https://bugs.chromium.org/p/v8/issues/detail?id=10041

**Comment by JanMarvin** [comment]
Fine with me. Just for the record: V8 release 8.4 should be around [very soon](https://v8.dev/blog) - without any configure flag. Version number in master was already bumped to 8.5.

**Comment by jeroen** [comment]
I've cleaned up the code a bit.

I hate they make us do this, but if there is not better solution from upstream by the time v8 8.4 is released, I will merge this.

**Comment by jeroen** [comment]
Can you test if this still works for you? I'm having a hard time building v8 from master again...

**Comment by JanMarvin** [comment]
Works for me, but you see the segfault every time you build (you can not `>>` it), my approach was to be silent

**Comment by jeroen** [comment]
OK thanks for clarifying, I restored your approach.

I just wasn't sure if wrapping the call in `{}` would change the exit code that we use in the next line, but I guess it works.

**Comment by jeroen** [comment]
I guess this won't be fixed upstream. Thanks for your help!

Can you confirm one more time everything is OK in the master branch now, then I'll submit to CRAN.

**Comment by JanMarvin** [comment]
Sure, I'll have a look later today

**Comment by jeroen** [comment]
Ok it's in cran now.

**Pull request merged**
