### PR TITLE
add configure option for pointer compression

### PR DESCRIPTION
**Pull request by JanMarvin**

### CODE REVIEW

**Comment by JanMarvin** [comment]
fixes #78

**Comment by jeroen** [comment]
Where did you read about COMPRESS_POINTERS_BOOL?

**Comment by JanMarvin** [comment]
I assumed it's defined here in recent v8, I just build 8.4.118, but my understanding of the configure script logic might be wrong

https://chromium.googlesource.com/v8/v8.git/+/2db93c0233790b2cfb9e80fa1fa89dee18c7109f%5E%21/#F0

**Comment by JanMarvin** [comment]
This does not work. The only way to check seems to be to run a small function with `v8::V8::Initialize()` and see if it crashes.

**Comment by kapouer** [comment]
@JanMarvin @jeroen [https://buildd.debian.org/status/fetch.php?pkg=r-cran-v8&arch=armhf&ver=3.1.0%2Bdfsg-1%2Bb1&stamp=1592149526&raw=0](it is failling on 32-bit archs ?).
Here's [a build summary where all failures are 32-bit](https://buildd.debian.org/status/package.php?p=r-cran-v8) when compiled against libv8-dev provided by libnode-dev version 12.18 in debian/sid.

**Comment by jeroen** [comment]
@kapouer sorry about that. I have pushed a fix into master: https://github.com/jeroen/V8/commit/a2f8a71f30c4ed900f89a961a097f8ba977856e4

You can get the raw patch file here: https://github.com/jeroen/V8/commit/a2f8a71f3.diff

Can you apply that patch directly in the deb or should I do an upstream release?

**Comment by kapouer** [comment]
I can apply that patch directly, thank you.

**Comment by jeroen** [comment]
OK awesome. Can you please confirm that it works (I tested it locally but I don't have x32 hw).

**Comment by kapouer** [comment]
It works on armhf. I'll know for sure on other archs after the debian builds happen.

**Comment by jeroen** [comment]
@kapouer FYI this patch is included in new upstream release V8 3.2.0.

**Pull request closed without merging**
